name = "avafe/moonlets"
version = "0.1.0"
authors = ["Avafe"]
license = "MIT"
private = true

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.2", target = "lune" }
selene = { name = "pesde/selene", version = "^0.28.0", target = "lune" }
