[package]
name = "imavafe/leader-stats"
description = "Wrapper object for player leaderstats"
version = "0.1.0"
license = "MIT"
authors = ["Avafe"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
