name = "avafe/humanoid_describer"
version = "0.1.1"
authors = ["Avafe"]
repository = "https://github.com/imavafe/moonlets"
license = "MIT"
private = true

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
Signal = { wally = "sleitnick/signal", version = "^2.0.1" }
Future = { wally = "red-blox/future", version = "^1.0.1" }
TableUtil = { wally = "sleitnick/table-util", version = "^1.2.1" }
